### ISSUE TITLE
Cannot add 2nd filter when signal has not been decimated

### ISSUE THREAD

**Issue by richardsim7** [3ll3d00d/beqdesigner#130]
Added one filter fine, but when I go to add a 2nd one, I get this:

Traceback (most recent call last): 
File "app.py", line 413, in addFilter 
File "model\filter.py", line 287, in __init__ 
File "model\filter.py", line 322, in previewFilter 
File "model\magnitude.py", line 147, in redraw 
File "model\magnitude.py", line 174, in __display_all_curves 
File "model\magnitude.py", line 45, in display_curves 
File "model\filter.py", line 333, in getMagnitudeData 
File "model\iir.py", line 730, in getTransferFunction 
File "model\iir.py", line 646, in getCascadeTransferFunction 
File "model\iir.py", line 646, in 
ValueError: operands could not be broadcast together with shapes (65536,) (8192,) 

Signal being used: https://www.dropbox.com/s/21mt5jsx5l5tztk/2001.signal?dl=0

**Comment by 3ll3d00d** [comment]
looks like you extracted at the original sample rate which I'm guessing is not what you intended to do

**Comment by richardsim7** [comment]
Ah, I should have used the "decimate audio" option I take it?

How about when adding a signal, should I select "resample" ?

**Comment by richardsim7** [comment]
Nevermind, I see when you select decimate audio, resample is ticked and greyed out - thanks, that works

**Comment by 3ll3d00d** [comment]
yes generally you want to decimate on extract when doing BEQ filters just to make the file sizes (and memory footprint) smaller
