### ISSUE TITLE
Problems with extracting

### ISSUE THREAD

**Issue by QuetzalcoaltD** [3ll3d00d/beqdesigner#188]
I did a clean windows install, with the latest ffmpeg and python, did the PATHs too. Tried the 0.5.5 "setup" build and the portable one including an old one (0.3.4 portable), when i choose a file to extract i get this:

Traceback (most recent call last): 
File "model\extract.py", line 115, in selectFile 
File "model\extract.py", line 160, in __probe_file 
File "model\ffmpeg.py", line 137, in probe_file 
File "site-packages\ffmpeg\_probe.py", line 16, in probe 
File "subprocess.py", line 709, in __init__ 
File "subprocess.py", line 997, in _execute_child 
FileNotFoundError: [WinError 2] The system cannot find the file specified 

Can't figure out whats wrong. Didn't have any problems before that.

**Comment by 3ll3d00d** [comment]
error just says that windows can't find whatever the file is

**Comment by QuetzalcoaltD** [comment]
The command given in FFmpeg site for setting the path, doesn't work, had to do it manually. Now it works ^_^. Didn't know which file was not found. Close it!

**Comment by 3ll3d00d** [comment]
You can either add the dir to the binaries to your path or tell the app where they are via the preferences screen
