### ISSUE TITLE
beqdesigner error when analyzing audio waveform with no filter

### ISSUE THREAD

**Issue by trhought** [3ll3d00d/beqdesigner#218]
Extracted .wav file into beqdesigner.  
Went into signal analysis dialogue box. 
Loaded the same .wav file into that dialogue box, 
Selected the LFE Channel (4 in this case).
Selected the "waveform" tab to look at waveform for LFE before the filter is applied
After looking at the signal, clicked on the filter drop down menu arrow and the below error was reported.
Later realized I didn't have a filter added in BEQd.  Once I add a filter in BEQd, then go to the analysis tool, the error doesn't happen and I can load the filter for any of the channels as shown in the drop-down menu.

Unexpected Error detected, go to https://github.com/3ll3d00d/beqdesigner/issues/new to log the issue
Traceback (most recent call last): 
File "model\analysis.py", line 299, in update_filter 
File "model\analysis.py", line 271, in show_chart 
File "model\analysis.py", line 309, in __get_filtered_signal 
File "model\signal.py", line 1023, in sosfilter 
File "site-packages\scipy\signal\signaltools.py", line 3237, in sosfilt 
File "site-packages\scipy\signal\filter_design.py", line 648, in _validate_sos 
ValueError: sos array must be shape (n_sections, 6)

**Comment by 3ll3d00d** [comment]
covered by #217
