### ISSUE TITLE
 0.7.3-beta.3 errors out

### ISSUE THREAD

**Issue by aron7awol** [3ll3d00d/beqdesigner#278]
beqdesigner_small.exe:

c:\users\travis\build\3ll3d00d\beqdesigner\.venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py:627: MatplotlibDeprecationWarning:
The MATPLOTLIBDATA environment variable was deprecated in Matplotlib 3.1 and will be removed in 3.3.
Traceback (most recent call last):
  File "site-packages\qtpy\__init__.py", line 202, in <module>
ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 18, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\travis\build\3ll3d00d\beqdesigner\.venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "model\waveform.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\travis\build\3ll3d00d\beqdesigner\.venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "site-packages\qtawesome\__init__.py", line 19, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\travis\build\3ll3d00d\beqdesigner\.venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "site-packages\qtawesome\iconic_font.py", line 24, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\travis\build\3ll3d00d\beqdesigner\.venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "site-packages\qtpy\__init__.py", line 208, in <module>
qtpy.PythonQtError: No Qt bindings could be found
[3036] Failed to execute script app

**Comment by aron7awol** [comment]
beqdesigner.exe:

c:\tools\miniconda3\envs\test\lib\site-packages\PyInstaller\loader\pyimod03_importers.py:627: MatplotlibDeprecationWarning:
The MATPLOTLIBDATA environment variable was deprecated in Matplotlib 3.1 and will be removed in 3.3.
Traceback (most recent call last):
  File "site-packages\qtpy\__init__.py", line 202, in <module>
ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 18, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\tools\miniconda3\envs\test\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "model\waveform.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\tools\miniconda3\envs\test\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "site-packages\qtawesome\__init__.py", line 19, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\tools\miniconda3\envs\test\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "site-packages\qtawesome\iconic_font.py", line 24, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\tools\miniconda3\envs\test\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "site-packages\qtpy\__init__.py", line 208, in <module>
qtpy.PythonQtError: No Qt bindings could be found
[1584] Failed to execute script app

**Comment by 3ll3d00d** [comment]
give https://github.com/3ll3d00d/beqdesigner/releases/tag/0.8.0-alpha.1 a try and see if that works

NB: that build has some other broken things (some windows don't open) but the core functionality (adding signals, filtering) should still work

I'm also curious to know if that build feels any slower (or faster) than the current one

**Comment by aron7awol** [comment]
Small version still gives me an error:

c:\users\travis\build\3ll3d00d\beqdesigner\.venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py:627: MatplotlibDeprecationWarning:
The MATPLOTLIBDATA environment variable was deprecated in Matplotlib 3.1 and will be removed in 3.3.
Traceback (most recent call last):
  File "app.py", line 18, in <module>
  File "c:\users\travis\build\3ll3d00d\beqdesigner\.venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "model\waveform.py", line 7, in <module>
ModuleNotFoundError: No module named 'pyqtgraph'
[2828] Failed to execute script app

**Comment by aron7awol** [comment]
The large version works but has the same SSL module missing error that caused me to have to move to the small version a while back because it couldn't download image from URL anymore.  Of course, this alpha build has the other issues that you are already aware of, such as the report window doesn't even show up so I can't download image from URL anyway :)

**Comment by aron7awol** [comment]
I'm not noticing a significant speed difference with the added median line, so that's good.
