### ISSUE TITLE
0.9.0-alpha.3 crashes at launch

### ISSUE THREAD

**Issue by aron7awol** [3ll3d00d/beqdesigner#295]
small.exe:

```
Traceback (most recent call last):
  File "app.py", line 11, in <module>
  File "c:\users\travis\build\3ll3d00d\beqdesigner\.venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "site-packages\matplotlib\__init__.py", line 138, in <module>
  File "c:\users\travis\build\3ll3d00d\beqdesigner\.venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "site-packages\matplotlib\cbook\__init__.py", line 31, in <module>
  File "c:\users\travis\build\3ll3d00d\beqdesigner\.venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "site-packages\numpy\__init__.py", line 150, in <module>
  File "c:\users\travis\build\3ll3d00d\beqdesigner\.venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "site-packages\numpy\random\__init__.py", line 180, in <module>
  File "mtrand.pyx", line 1, in init numpy.random.mtrand
ModuleNotFoundError: No module named 'numpy.random.common'
[15920] Failed to execute script app
```

**Comment by 3ll3d00d** [comment]
try this one -> https://github.com/3ll3d00d/beqdesigner/releases/download/0.7.3-beta.12/beqdesigner.exe

it works for me
