### ISSUE TITLE
Error when editing filter is back in 0.9.0 beta3

### ISSUE THREAD

**Issue by aron7awol** [3ll3d00d/beqdesigner#304]
Unexpected Error detected, go to https://github.com/3ll3d00d/beqdesigner/issues/new to log the issue
AttributeError: __getattribute__ 
The above exception was the direct cause of the following exception: 
Traceback (most recent call last): 
File "app.py", line 587, in editFilter 
File "model\filter.py", line 249, in __init__ 
File "ui\filter.py", line 174, in setupUi 
SystemError: returned a result with an error set

**Comment by 3ll3d00d** [comment]
0.9.0-beta.4 coming up soon
