### ISSUE TITLE
mkv file, can't load :-(

### ISSUE THREAD

**Issue by michaelbarkan** [3ll3d00d/beqdesigner#321]
Unexpected Error detected, go to https://github.com/3ll3d00d/beqdesigner/issues/new to log the issue
Traceback (most recent call last): 
File "model\extract.py", line 108, in selectFile 
File "model\extract.py", line 211, in __probe_file 
File "model\ffmpeg.py", line 330, in probe_file 
File "site-packages\ffmpeg\_probe.py", line 20, in probe 
File "subprocess.py", line 775, in __init__ 
File "subprocess.py", line 1178, in _execute_child 
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by michaelbarkan** [comment]
Files are in a folder on desktop, no problem playing, just can't load (extract audio) into beq
