### ISSUE TITLE
The system cannot find the file specified 

### ISSUE THREAD

**Issue by paulst1976** [3ll3d00d/beqdesigner#322]
Traceback (most recent call last): 
File "model\extract.py", line 108, in selectFile 
File "model\extract.py", line 211, in __probe_file 
File "model\ffmpeg.py", line 330, in probe_file 
File "site-packages\ffmpeg\_probe.py", line 20, in probe 
File "subprocess.py", line 800, in __init__ 
File "subprocess.py", line 1207, in _execute_child 
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by 3ll3d00d** [comment]
Not enough info here to comment

**Comment by paulst1976** [comment]
Was while attempting to extract audio.. that's all there was..

**Comment by 3ll3d00d** [comment]
Well the error is clear, windows can't find (or read) whatever file you are looking for. This means either ffmpeg or the file itself.

**Comment by paulst1976** [comment]
Thanks, think the 1903 windows update caused it, removed the binaries for ffmpeg and also the default output for extraction, seems to have fixed it
