### ISSUE TITLE
trying to load MKV for Remux:  "the system cannot find the file specific" 

### ISSUE THREAD

**Issue by drew-fitcraft** [3ll3d00d/beqdesigner#329]
getting this error on any MKV I try to load in the Remux Audio feature.
I've tried running as admin as well.
thanks for your support.

Unexpected Error detected, go to https://github.com/3ll3d00d/beqdesigner/issues/new to log the issue
Traceback (most recent call last): 
File "model\extract.py", line 108, in selectFile 
File "model\extract.py", line 211, in __probe_file 
File "model\ffmpeg.py", line 330, in probe_file 
File "site-packages\ffmpeg\_probe.py", line 20, in probe 
File "subprocess.py", line 800, in __init__ 
File "subprocess.py", line 1207, in _execute_child 
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by 3ll3d00d** [comment]
Do you have ffmpeg installed and configured in settings?

**Comment by paulst1976** [comment]
This is what happened to me after a Windows update, it was the ffmpeg directory disappearing, under preferences/binaries..
