### ISSUE TITLE
Latest build fails with dll error

### ISSUE THREAD

**Issue by 3ll3d00d** [3ll3d00d/beqdesigner#362]
```
Microsoft Windows [Version 10.0.18363.778]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\Mike>"C:\Program Files\beqdesigner\beqdesigner.exe"
c:\tools\miniconda3\envs\test\lib\site-packages\PyInstaller\loader\pyimod03_importers.py: 623: MatplotlibDeprecationWarning:
The MATPLOTLIBDATA environment variable was deprecated in Matplotlib 3.1 and will be removed in 3.3.
Traceback (most recent call last):
File "site-packages\numba\core\typeconv\typeconv.py", line 4, in <module>
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "app.py", line 25, in <module>
File "c:\tools\miniconda3\envs\test\lib\site-packages\PyInstaller\loader\pyimod03_importers.py" , line 623, in exec_module
File "model\waveform.py", line 15, in <module>
File "c:\tools\miniconda3\envs\test\lib\site-packages\PyInstaller\loader\pyimod03_importers.py" , line 623, in exec_module
File "model\signal.py", line 13, in <module>
File "c:\tools\miniconda3\envs\test\lib\site-packages\PyInstaller\loader\pyimod03_importers.py" , line 623, in exec_module
File "site-packages\resampy\__init__.py", line 7, in <module>
File "c:\tools\miniconda3\envs\test\lib\site-packages\PyInstaller\loader\pyimod03_importers.py" , line 623, in exec_module
File "site-packages\resampy\core.py", line 9, in <module>
File "c:\tools\miniconda3\envs\test\lib\site-packages\PyInstaller\loader\pyimod03_importers.py" , line 623, in exec_module
File "site-packages\resampy\interpn.py", line 4, in <module>
File "c:\tools\miniconda3\envs\test\lib\site-packages\PyInstaller\loader\pyimod03_importers.py" , line 623, in exec_module
File "site-packages\numba\__init__.py", line 20, in <module>
File "c:\tools\miniconda3\envs\test\lib\site-packages\PyInstaller\loader\pyimod03_importers.py" , line 623, in exec_module
File "site-packages\numba\misc\special.py", line 3, in <module>
File "c:\tools\miniconda3\envs\test\lib\site-packages\PyInstaller\loader\pyimod03_importers.py" , line 623, in exec_module
File "site-packages\numba\core\typing\__init__.py", line 1, in <module>
File "c:\tools\miniconda3\envs\test\lib\site-packages\PyInstaller\loader\pyimod03_importers.py" , line 623, in exec_module
File "site-packages\numba\core\typing\context.py", line 11, in <module>
File "c:\tools\miniconda3\envs\test\lib\site-packages\PyInstaller\loader\pyimod03_importers.py" , line 623, in exec_module
File "site-packages\numba\core\typeconv\rules.py", line 2, in <module>
File "c:\tools\miniconda3\envs\test\lib\site-packages\PyInstaller\loader\pyimod03_importers.py" , line 623, in exec_module
File "site-packages\numba\core\typeconv\typeconv.py", line 17, in <module>
ImportError: Numba could not be imported.
If you are seeing this message and are undertaking Numba development work, you may need to re-run:

python setup.py build_ext --inplace

(Also, please check the development set up guide http://numba.pydata.org/numba-doc/latest/developer/contributing.html.)

If you are not working on Numba development:

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!

The original error was: 'DLL load failed: The specified module could not be found.'
--------------------------------------------------------------------------------
If possible please include the following in your error report:

sys.executable: C:\Program Files\beqdesigner\beqdesigner.exe

[6864] Failed to execute script app
```

**Comment by 3ll3d00d** [comment]
affects the latest beta19 build only

**Comment by 3ll3d00d** [comment]
numba upgraded from 0.48 to 0.49

**Comment by Foundation2nd** [comment]
check this one and beta18 works for me, only 19 has this issue.

**Comment by 3ll3d00d** [comment]
due to https://github.com/numba/numba/issues/5600
