### ISSUE TITLE
v.0.9.4 Unable to extract Audio 

### ISSUE THREAD

**Issue by cypaq** [3ll3d00d/beqdesigner#367]
Traceback (most recent call last): 
File "model\extract.py", line 108, in selectFile 
File "model\extract.py", line 214, in __probe_file 
File "model\ffmpeg.py", line 341, in probe_file 
File "site-packages\ffmpeg\_probe.py", line 20, in probe 
File "subprocess.py", line 800, in __init__ 
File "subprocess.py", line 1207, in _execute_child 
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by 3ll3d00d** [comment]
The usual reason for this is that you have not configured or installed ffmpeg 

https://beqdesigner.readthedocs.io/en/latest/install/#optional-dependencies

**Comment by cypaq** [comment]
Got it to work again. Thanks.
