### ISSUE TITLE
Error using Reset on the Merge UI

### ISSUE THREAD

**Issue by Foundation2nd** [3ll3d00d/beqdesigner#385]
I received the following error when I pressed Reset on the Merge UI to refresh the files.  After getting the error, I noticed that I had the target directory open in a separate Explorer window.  After I closed it and tried the Reset again, it ran fine.

```
Unexpected Error detected, go to https://github.com/3ll3d00d/beqdesigner/issues/new to log the issue
Traceback (most recent call last): 
File "model\merge.py", line 102, in __force_clone 
File "shutil.py", line 516, in rmtree 
File "shutil.py", line 395, in _rmtree_unsafe 
File "shutil.py", line 404, in _rmtree_unsafe 
File "shutil.py", line 402, in _rmtree_unsafe 
OSError: [WinError 145] The directory is not empty: 'C:\\Users\\Mike\\.beq\\bmiller_miniDSPBEQ' 
```

**Comment by 3ll3d00d** [comment]
this is normal behaviour on windows because of how windows locks files, not much to be done about this I'm afraid.
