### ISSUE TITLE
Error, cannot merge files. 

### ISSUE THREAD

**Issue by aoaaron** [3ll3d00d/beqdesigner#428]
Trying to merge files, it comes up with this error: 

Unexpected Error detected, go to https://github.com/3ll3d00d/beqdesigner/issues/new to log the issue
Traceback (most recent call last): 
File "app.py", line 1021, in merge_minidsp_xml 
File "model\merge.py", line 62, in __init__ 
File "model\merge.py", line 135, in update_beq_count 
File "glob.py", line 21, in glob 
File "glob.py", line 73, in _iglob 
File "glob.py", line 74, in _iglob 
File "glob.py", line 112, in _glob2 
File "glob.py", line 140, in _rlistdir 
File "glob.py", line 140, in _rlistdir 
File "glob.py", line 140, in _rlistdir 
[Previous line repeated 984 more times] 
File "glob.py", line 139, in _rlistdir 
File "ntpath.py", line 90, in join 
File "ntpath.py", line 143, in splitdrive 
RecursionError: maximum recursion depth exceeded while calling a Python object 

This is on all builds of BEQ I've tried. Any fix?

**Comment by 3ll3d00d** [comment]
this is most likely an error in your configuration, you must have the "User Source Directory" set to something for this to happen
