### ISSUE TITLE
Unexpected Error detected

### ISSUE THREAD

**Issue by Philotto** [3ll3d00d/beqdesigner#444]
Traceback (most recent call last): 
File "model\extract.py", line 108, in selectFile 
File "model\extract.py", line 214, in __probe_file 
File "model\ffmpeg.py", line 341, in probe_file 
File "ffmpeg\_probe.py", line 23, in probe 
ffmpeg._run.Error: ffprobe error (see stderr output for detail)

**Comment by 3ll3d00d** [comment]
there's not enough info, as it says

`ffmpeg._run.Error: ffprobe error (see stderr output for detail)`

so need that stderr output, it's some ffmpeg error anyway

**Comment by Philotto** [comment]
Thanks, i have resolved reinstalling ffmpeg

Il mar 15 mar 2022, 22:19 Matt Khan ***@***.***> ha scritto:
