### ISSUE TITLE
Issue with Browse Catalogue

### ISSUE THREAD

**Issue by digimaster69** [3ll3d00d/beqdesigner#450]
Hi,
in Browse Catalogue, I have the following issue:

First error message:

Traceback (most recent call last): 
File "app.py", line 1012, in show_catalogue 
File "model\catalogue.py", line 89, in __init__ 
File "sortedcontainers\sortedset.py", line 234, in __getitem__ 
File "sortedcontainers\sortedlist.py", line 891, in __getitem__ 
IndexError: list index out of range

Second Error Message:

Traceback (most recent call last): 
File "model\catalogue.py", line 379, in run 
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Marco\\.beq\\database.csv'

**Comment by 3ll3d00d** [comment]
does that file exist?

i.e. `C:\Users\Marco\.beq\database.csv`

if so, what is in it?
