### ISSUE TITLE
unexpected error detected

### ISSUE THREAD

**Issue by jt23738** [3ll3d00d/beqdesigner#453]
happens when I want to analyze an extracted audio file with a filter

Traceback (most recent call last): 
File "model\analysis.py", line 273, in load_file 
File "model\analysis.py", line 297, in show_chart 
File "model\analysis.py", line 685, in analyse 
File "model\analysis.py", line 781, in __cache_xyz 
TypeError: flatten() missing 1 required positional argument: 'items'

**Comment by 3ll3d00d** [comment]
Which version are you using?
What exactly does analyze an extracted audio file with a filter mean? Step by step instructions to reproduce would be best

**Comment by jt23738** [comment]
[0.11.0-beta.12] same error occurs on beta 11 , went back to 11.0 beta.10  and I was able to analyze my audio file

I'm using the latest up to date windows 10
I extract audio in beq designer from my mp4 videos, use decimate audio and mix to mono, then load the signal and create a filters for the audio. Then I chose the extracted signal file with the created filter in beq using ctrl + a, when i click load the error message happens.

**Comment by 3ll3d00d** [comment]
should be fixed in 0.11.0-beta.13
