### ISSUE TITLE
Invalid Rendering

### ISSUE THREAD

**Issue by artiko88** [3ll3d00d/beqdesigner#454]
Hey!

Whenever i make any change to the settings for JRiver, i get this message:

![image](https://user-images.githubusercontent.com/4704439/224809915-f1a09a2b-d993-4932-985b-1de9e38a1b3c.png)

Any chance this issue can be resolved?

**Comment by 3ll3d00d** [comment]
is this a configuration you're creating in beqd or something you downloaded from media center?

btw you're doing a lot of manual copy operations, this is what the crossover filter is there to do for you

**Comment by artiko88** [comment]
Hey!

So i installed latest version from this page -
https://github.com/3ll3d00d/beqdesigner/releases

I start the application, go to Tools -> Manage JMC Filters, create a new
project, choose version 28, 10 channels and it produces this error message.
Then, whenever i try to add a filter, it shows this message. I do see
graphs at the bottom part of the windows, but never in the central part.

**Comment by 3ll3d00d** [comment]
Ok so it is a problem with your machine

you need to look in the logs to find the error and post it here.

**Comment by artiko88** [comment]
Here is what i found in the logs:
https://pastebin.com/JrunuuUm

I suspect that it cannot parse string to floats because of difference in
decimal sign. It gets a coma instead of a dot.But who knows.

**Comment by 3ll3d00d** [comment]
What locale do you use?

**Comment by 3ll3d00d** [comment]
2 problems in the log

given a valid graph

```
digraph G {
  rankdir=LR;
  node [
    shape="box"
    color="#000000"
    fontcolor="#000000"
  ];
  edge [
    color="#000000"
  ];
  graph [
    color="#000000"
    fontcolor="#000000"
  ];
 
  IN [shape=record label="<L> L|<R> R|<C> C|<SW> SW|<RL> RL|<RR> RR|<SL> SL|<SR> SR"];
  OUT [shape=record label="<L> L|<R> R|<C> C|<SW> SW|<SL> SL|<SR> SR|<RL> RL|<RR> RR|<C9> C9|<C10> C10"];
 
 
 
  IN:L -> OUT:L;
  IN:R -> OUT:R;
  IN:C -> OUT:C;
  IN:SW -> OUT:SW;
  IN:SL -> OUT:SL;
  IN:SR -> OUT:SR;
  IN:RL -> OUT:RL;
  IN:RR -> OUT:RR;
}
```

an error is produced

```
Traceback (most recent call last):
  File "model\jriver\ui.py", line 1096, in __regen
  File "model\jriver\ui.py", line 1117, in __gen_svg
  File "model\jriver\render.py", line 185, in render_dot
  File "graphviz\piping.py", line 104, in pipe
  File "graphviz\_tools.py", line 171, in wrapper
  File "graphviz\piping.py", line 121, in _pipe_legacy
  File "graphviz\piping.py", line 161, in _pipe_future
  File "graphviz\backend\piping.py", line 161, in pipe_lines
  File "graphviz\backend\execute.py", line 88, in run_check
  File "graphviz\backend\execute.py", line 114, in _write_stderr
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcd in position 90: invalid continuation byte
```

and when loading from MC

```
2023-03-14 15:46:55,799 - ERROR - MainThread	- jriver.ui - __load_dsp - Unable to parse Player
Traceback (most recent call last):
  File "model\jriver\ui.py", line 263, in __load_dsp
  File "model\jriver\dsp.py", line 38, in __init__
  File "model\jriver\dsp.py", line 82, in __parse_peq
  File "model\jriver\dsp.py", line 82, in <listcomp>
  File "model\jriver\filter.py", line 1271, in create_single_filter
  File "model\jriver\filter.py", line 277, in __init__
  File "model\jriver\filter.py", line 213, in __init__
ValueError: could not convert string to float: '-3,4900000000000002'
```

**Comment by 3ll3d00d** [comment]
I can fix the latter, the former looks trickier as it's coming out of a 3rd party library (graphviz)

**Comment by artiko88** [comment]
Will try it on another machine. Maybe it will work.

As for the second error with import from MC - Would something like using a
locale module for python fix the error?
I can try switching the decimal point setting with a bat file before and
after starting the beqdesigner, but that is quite a crutch.
But if you can fix this, that would be lovely!

**Comment by 3ll3d00d** [comment]
Yes exactly, the bit of code blowing has no locale aware parsing so blows up. I will fix in next release.

**Comment by artiko88** [comment]
Switching Locale to US and going by this advice i found on the interwebz fixed the problem:

`In the 1809 build of Windows 10 I've managed to permanently solve this by going to the system's Language settings, selecting Administrative language settings, clicking Change system locale... and checking the Beta: Use Unicode UTF-8 for worldwide language support box and then restarting my pc.`

Now it correctly downloads data from JRiver and renders the diagram. Wow, what a cool tool!

BTW, the Source function from graphviz supports 'encoding' parameter. By default it expects utf-8, but can be set as a string parameter. Maybe feeding default Windows setting would solve such problem:

```
def render_dot(txt):
    from graphviz import Source
    encoding = get_default_windows_encoding_somehow()
    return Source(txt, encoding = encoding, format='svg').pipe()
```

 I never tried it because i found a faster route to fix my issue :)

**Comment by 3ll3d00d** [comment]
https://stackoverflow.com/a/68066008/123054 gives an answer to what that option does

https://stackoverflow.com/questions/66137468/how-to-get-the-codepage-currently-used-in-local-computer suggests how to get the info from the host

I'm not sure exactly what is failing though, e.g. is it the stdin/out/err comms which is failing or the source content I generate? some testing would be required to work that out so not sure this will get fixed quickly

**Comment by 3ll3d00d** [comment]
fix for the jriver dsp parsing is in https://github.com/3ll3d00d/beqdesigner/releases/tag/0.11.0-beta.20
