### ISSUE TITLE
Can't select files

### ISSUE THREAD

**Issue by GurvanBHC** [3ll3d00d/beqdesigner#460]
Traceback (most recent call last): 
File "model\extract.py", line 108, in selectFile 
File "model\extract.py", line 214, in __probe_file 
File "model\ffmpeg.py", line 341, in probe_file 
File "ffmpeg\_probe.py", line 20, in probe 
File "subprocess.py", line 951, in __init__ 
File "subprocess.py", line 1420, in _execute_child 
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable

**Comment by 3ll3d00d** [comment]
Typically means you don't have ffmpeg installed/configured 

https://beqdesigner.readthedocs.io/en/latest/ui/preferences/#ffmpeg
