### ISSUE TITLE
.

### ISSUE THREAD

**Issue by GurvanBHC** [3ll3d00d/beqdesigner#461]
Traceback (most recent call last): 
File "app.py", line 856, in normaliseSignalMagnitude 
File "model\magnitude.py", line 325, in normalise 
File "model\magnitude.py", line 228, in redraw 
File "model\magnitude.py", line 267, in __display_all_curves 
File "model\magnitude.py", line 54, in display_curves 
File "model\signal.py", line 762, in get_curve_data 
File "model\signal.py", line 762, in 
File "model\xy.py", line 131, in normalise 
File "model\xy.py", line 29, in __init__ 
File "model\xy.py", line 206, in smooth 
File "model\xy.py", line 221, in smooth_octave 
File "acoustics\smooth.py", line 250, in fractional_octaves 
File "acoustics\smooth.py", line 138, in __init__ 
ValueError: Given center frequencies are not equally spaced.

**Comment by 3ll3d00d** [comment]
Posting a stack trace on its own is basically useless. If I can't reproduce it using explicit instructions then nothing further will happen.
