### ISSUE TITLE
Upload Image on Report

### ISSUE THREAD

**Issue by Philotto** [3ll3d00d/beqdesigner#463]
Hi, when i try to upload an Image from URL i get this error: 

```
Traceback (most recent call last): 
File "model\report.py", line 787, in load_image_from_url 
File "model\report.py", line 712, in apply_image 
File "matplotlib\image.py", line 1563, in imread 
File "PIL\Image.py", line 3280, in open 
PIL.UnidentifiedImageError: cannot identify image file 'D:\\TEMP\\tmpccvwki15.jpg' 
```

If i download those image then can be uploaded , but when i try to make them pixel-perfect on layout, then give me this error:

```
Traceback (most recent call last): 
File "model\report.py", line 117, in redraw_all_axes 
File "model\magnitude.py", line 200, in __init__ 
File "model\limits.py", line 189, in propagate_to_axes 
File "model\magnitude.py", line 222, in __redraw_func 
File "model\report.py", line 151, in on_redraw 
File "matplotlib\image.py", line 977, in set_extent 
AttributeError: 'NoneType' object has no attribute '_process_unit_info' 
```

**Comment by 3ll3d00d** [comment]
splitting this to a different issue

> Hi, when i try to upload an Image from URL i get this error:
> 
> ```
> Traceback (most recent call last): 
> File "model\report.py", line 787, in load_image_from_url 
> File "model\report.py", line 712, in apply_image 
> File "matplotlib\image.py", line 1563, in imread 
> File "PIL\Image.py", line 3280, in open 
> PIL.UnidentifiedImageError: cannot identify image file 'D:\\TEMP\\tmpccvwki15.jpg' 
> ```

**Comment by Philotto** [comment]
Ok, the first is solved (very annoying, upload from the site where i redirect the URL has been ok few months ago, and has a lot of material).

Regarding to the second error, it is better if i create another "issue" or can we discuss here? 

"If i download those image then can be uploaded , but when i try to make them pixel-perfect on layout, then give me this error:

Traceback (most recent call last): 
File "model\report.py", line 117, in redraw_all_axes 
File "model\magnitude.py", line 200, in __init__ 
File "model\limits.py", line 189, in propagate_to_axes 
File "model\magnitude.py", line 222, in __redraw_func 
File "model\report.py", line 151, in on_redraw 
File "matplotlib\image.py", line 977, in set_extent 
AttributeError: 'NoneType' object has no attribute '

**Comment by 3ll3d00d** [comment]
It fixed already hence why I closed this

**Comment by Philotto** [comment]
Oh sorry, i didn't understand! I have downloaded the latest pre-release 1.0.1 and can confirm it's ok ! Sorry
