### ISSUE TITLE
Suddenly cannot extract audio anymore

### ISSUE THREAD

**Issue by TythorZeth** [3ll3d00d/beqdesigner#475]
Hey bro,

I suddenly get this error when I use the Extract Audio function, select a file and click on Open. It doesn't even get to the point where I can extract it. I tried several files and I have the same problem with previous versions. This newest version was working fine last night as well...

Traceback (most recent call last): 
File "model\extract.py", line 108, in selectFile 
File "model\extract.py", line 214, in __probe_file 
File "model\ffmpeg.py", line 341, in probe_file 
File "ffmpeg\_probe.py", line 20, in probe 
File "subprocess.py", line 1026, in __init__ 
File "subprocess.py", line 1538, in _execute_child 
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by 3ll3d00d** [comment]
error usually means ffprobe is not on your path or isn't configured in beqd preferences

**Comment by TythorZeth** [comment]
I knew it was something stupid... Ffmpeg was not functioning properly, I reinstalled it and now it's working fine. Thank you <3
