### ISSUE TITLE
Multi-Sub Optimizer, import fails

### ISSUE THREAD

**Issue by HyggeJJ** [3ll3d00d/beqdesigner#477]
When trying to import a mains+sub configuration from MSO, I get the following error in BEQ v1.1.7.

Traceback (most recent call last): 
File "model\jriver\ui.py", line 1268, in __select_filter 
File "model\jriver\parser.py", line 53, in from_mso 
File "model\jriver\parser.py", line 106, in convert_mso_filter 
File "model\jriver\filter.py", line 1321, in convert_filter_to_mc_dsp 
File "model\jriver\filter.py", line 614, in __init__ 
File "model\jriver\__init__.py", line 36, in s2f 
AttributeError: 'float' object has no attribute 'replace' 

The JSON file from MSO:
[2024-12-20a LLW665+Subs 12th.oct.json](https://github.com/user-attachments/files/18220249/2024-12-20a.LLW665%2BSubs.12th.oct.json)

**Comment by HyggeJJ** [comment]
Fixed in 1.1.10.
